CREATE TABLE articulos (
  id INTEGER AUTO_INCREMENT  PRIMARY KEY,
  ean VARCHAR(30) NOT NULL,
  importe INT NOT NULL,
  talla VARCHAR(250) NOT NULL,
  color VARCHAR(250) NOT NULL,
  nombre VARCHAR(250) NOT NULL
);